[workspace]
resolver = "2"
members = [
    "crates/core"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["DataScienceBioLab"]
description = "A modular and maintainable Rust project"

# Linting configuration for development
[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
dead_code = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "allow", priority = -1 }
complexity = { level = "allow", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }

# Additional specific lints
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
clone_on_ref_ptr = "warn"
cognitive_complexity = "warn"
doc_markdown = "warn"
empty_enum = "warn"
enum_glob_use = "warn"
explicit_into_iter_loop = "warn"
explicit_iter_loop = "warn"
fallible_impl_from = "warn"
future_not_send = "warn"
if_not_else = "warn"
implicit_clone = "warn"
implicit_saturating_sub = "warn"
indexing_slicing = "warn"
manual_assert = "warn"
manual_ok_or = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
must_use_candidate = "warn"
needless_borrow = "warn"
needless_continue = "warn"
needless_for_each = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
unused_self = "warn"
useless_transmute = "warn"

# Allow some very common patterns
module_name_repetitions = "allow"
too_many_lines = "allow"
similar_names = "allow"

[workspace.dependencies]
# Core dependencies
tokio = { version = "1.36", features = ["full"] }
futures = { version = "0.3" }
async-trait = { version = "0.1" }
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sled = "0.34"
rand = "0.8"
ring = "0.17"

# Monitoring and logging
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }

# MCP dependencies
bytes = { version = "1.5" }
futures-util = { version = "0.3" }
tokio-util = { version = "0.7", features = ["codec"] }

# Testing dependencies
tokio-test = "0.4"
mockall = "0.12"
criterion = "0.5"
insta = "1.36"
snapbox = "0.5" 