[workspace]
resolver = "2"
members = [
    "crates/core"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["DataScienceBioLab"]
description = "A modular and maintainable Rust project"

# Linting configuration for development
[workspace.lints.rust]
missing_docs = "allow"
missing_debug_implementations = "allow"
missing_copy_implementations = "allow"
dead_code = "allow"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
cargo = "allow"
complexity = "allow"
perf = "warn"
style = "warn"
suspicious = "warn"

[workspace.dependencies]
# Core dependencies
tokio = { version = "1.36", features = ["full"] }
futures = { version = "0.3" }
async-trait = { version = "0.1" }
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.7", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sled = "0.34"

# Monitoring and logging
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }

# MCP dependencies
bytes = { version = "1.5" }
futures-util = { version = "0.3" }
tokio-util = { version = "0.7", features = ["codec"] }

# Testing dependencies
tokio-test = "0.4"
mockall = "0.12"
criterion = "0.5"
insta = "1.36"
snapbox = "0.5" 