[workspace]
resolver = "2"
members = [
    "crates/core"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["DataScienceBioLab"]
description = "A modular and maintainable Rust project"

# Linting configuration for development
[workspace.lints.rust]
missing_docs = "warn"
missing_debug_implementations = "warn"
missing_copy_implementations = "warn"
dead_code = "allow"
type_complexity = "allow"

[workspace.lints.clippy]
# General categories
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
complexity = { level = "warn", priority = -1 }
perf = { level = "warn", priority = -1 }
style = { level = "warn", priority = -1 }
suspicious = { level = "warn", priority = -1 }

# Specific lints
cast-possible-truncation = "allow"
cast-possible-wrap = "allow"
cast-precision-loss = "allow"
cast-sign-loss = "allow"
clone-on-ref-ptr = "warn"
cognitive-complexity = "warn"
doc-markdown = "warn"
empty-enum = "warn"
enum-glob-use = "warn"
explicit-into-iter-loop = "warn"
explicit-iter-loop = "warn"
fallible-impl-from = "warn"
future-not-send = "warn"
if-not-else = "warn"
implicit-clone = "warn"
implicit-saturating-sub = "warn"
indexing-slicing = "warn"
manual-assert = "warn"
manual-ok-or = "warn"
missing-errors-doc = "warn"
missing-panics-doc = "warn"
must-use-candidate = "warn"
needless-borrow = "warn"
needless-continue = "warn"
needless-for-each = "warn"
redundant-else = "warn"
semicolon-if-nothing-returned = "warn"
unused-self = "warn"
useless-transmute = "warn"
module-name-repetitions = "allow"
too-many-lines = "allow"
similar-names = "allow"
significant-drop-tightening = "allow"
unused-async = "warn"
raw-string-hashes = "allow"

# Enforce documentation standards
missing_docs_in_private_items = "warn"
undocumented_unsafe_blocks = "warn"
todo = "warn"

[workspace.dependencies]
# Core dependencies
tokio = { version = "1.0", features = ["full"] }
futures = { version = "0.3" }
async-trait = { version = "0.1" }
thiserror = "1.0"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sled = "0.34"
time = { version = "0.3", features = ["serde"] }
metrics = "0.21"
metrics-exporter-prometheus = "0.12"
prometheus = "0.13"
hyper = { version = "0.14", features = ["full"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
chrono = { version = "0.4", features = ["serde"] }
sysinfo = "0.29"
lazy_static = "1.4"
ring = "0.17"
rand = "0.8"

# Monitoring and logging
tracing = "0.1"
tracing-subscriber = "0.3"

# MCP dependencies
bytes = "1.5"
futures-util = "0.3"
tokio-util = { version = "0.7", features = ["codec"] }

# Compression dependencies
zstd = { version = "0.13", features = ["zstdmt"] }
flate2 = { version = "1.0", features = ["zlib"] }
lz4 = "1.24"

# Notification system dependencies
reqwest = { version = "0.11", features = ["json"] }
handlebars = "4.3"
lettre = { version = "0.10", features = ["tokio1", "tokio1-native-tls"] }

# Dashboard server dependencies
axum = { version = "0.6", features = ["ws"] }
tower-http = { version = "0.4", features = ["cors"] }
tokio-tungstenite = "0.20"
tower = "0.4"

# Testing dependencies
tokio-test = "0.4"
test-context = "0.1"
mockall = "0.11"
criterion = "0.5"
insta = "1.36"
snapbox = "0.5"
tempfile = "3.8" 