# Temporarily relaxed configuration during refactoring
warn-on-all-wildcard-imports = false
too-many-arguments-threshold = 10
cognitive-complexity-threshold = 30
type-complexity-threshold = 500
too-many-lines-threshold = 150

# Disable some strict lints during refactoring
[lints]
missing_docs = "allow"
missing_debug_implementations = "allow"
missing_copy_implementations = "allow"
dead_code = "allow"
unused_imports = "warn"
unused_variables = "warn"

# Allow some common development patterns
cognitive-complexity-threshold = 30
too-many-arguments-threshold = 10
type-complexity-threshold = 500

# Disable some overly strict checks during development
doc-valid-idents = false
missing-errors-doc = false
missing-panics-doc = false
module-name-repetitions = false
must-use-candidate = false
similar-names = false 