# Example configuration file for the Code Analysis and Reporting System

[web]
bind_address = "127.0.0.1"
port = 3000
database_url = "postgres://user:password@localhost/code_analysis"

[web.cors]
allowed_origins = ["http://localhost:3000"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization"]

[mcp]
bind_address = "127.0.0.1"
port = 50051
max_connections = 100

[mcp.tls]
enabled = false
cert_path = "certs/server.crt"
key_path = "certs/server.key"

[analysis]
# Default analysis configuration
security_scan = true
performance_scan = true
style_scan = true
max_depth = 10

[analysis.rules]
# Paths to rule configuration files
security = "rules/security.toml"
performance = "rules/performance.toml"
style = "rules/style.toml"

[reporting]
# Default report configuration
default_format = "markdown"
default_template = "templates/default.md"
include_summary = true
include_details = true
include_recommendations = true

[reporting.templates]
markdown = "templates/markdown/"
html = "templates/html/"
pdf = "templates/pdf/"

[logging]
level = "info"
format = "json"
file = "logs/system.log"

[metrics]
enabled = true
prometheus_port = 9090

[security]
# Authentication configuration
jwt_secret = "your-secret-key"
token_expiry_hours = 24

[database]
# PostgreSQL connection pool configuration
max_connections = 5
min_connections = 1
max_lifetime_secs = 1800
idle_timeout_secs = 600

[cache]
enabled = true
type = "redis"
url = "redis://localhost:6379"
ttl_secs = 3600

[storage]
# File storage configuration
type = "local"
path = "data/storage"
max_size_mb = 1000

[git]
# Git repository configuration
clone_path = "data/repos"
timeout_secs = 300
max_size_mb = 500 