[package]
name = "squirrel-test-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Test utilities for Squirrel"

# Specify a different name for the di_test_program binary
[[bin]]
name = "test_utils_di_test_program"
path = "src/bin/di_test_program.rs"

[dependencies]
# Core dependencies
tokio = { workspace = true, features = ["full"] }
futures = { workspace = true }
async-trait = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tempfile = { workspace = true }
rand = { version = "0.8.5" }
reqwest = { version = "0.11", features = ["json"] }
anyhow = { workspace = true }

# Shared squirrel dependencies
squirrel-core = { path = "../core" }
squirrel-context = { path = "../context" }
squirrel-mcp = { path = "../mcp" }
squirrel-monitoring = { path = "../monitoring" }
squirrel-commands = { path = "../commands" }

[dev-dependencies]
tokio-test = { workspace = true }

[lib]
name = "squirrel_test_utils"
path = "src/lib.rs" 