[target.'cfg(all())']
rustflags = [
    "-D", "warnings",
    "-D", "missing_docs",
    "-D", "missing_debug_implementations",
    "-D", "missing_copy_implementations",
    "-D", "unsafe_code",
    "-D", "unstable_features",
    "-D", "unused_imports",
    "-D", "unused_must_use",
    "-D", "unused_mut",
    "-D", "unused_unsafe",
    "-D", "unused_variables",
    "-D", "bare_trait_objects",
    "-D", "elided_lifetimes_in_paths",
    "-D", "explicit_outlives_requirements",
    "-D", "keyword_idents",
    "-D", "macro_use_extern_crate",
    "-D", "non_ascii_idents",
    "-D", "private_doc_tests",
    "-D", "rust_2018_idioms",
    "-D", "single_use_lifetimes",
    "-D", "trivial_casts",
    "-D", "trivial_numeric_casts",
    "-D", "unreachable_pub",
    "-D", "unsafe_op_in_unsafe_fn",
    "-D", "unused_extern_crates",
    "-D", "unused_lifetimes",
    "-D", "unused_results",
    "-D", "variant_size_differences"
]

[target.'cfg(test)']
rustflags = [
    "-D", "warnings",
    "-D", "missing_docs",
    "-D", "missing_debug_implementations",
    "-D", "missing_copy_implementations",
    "-D", "unsafe_code",
    "-D", "unstable_features",
    "-D", "unused_imports",
    "-D", "unused_must_use",
    "-D", "unused_mut",
    "-D", "unused_unsafe",
    "-D", "unused_variables",
    "-D", "bare_trait_objects",
    "-D", "elided_lifetimes_in_paths",
    "-D", "explicit_outlives_requirements",
    "-D", "keyword_idents",
    "-D", "macro_use_extern_crate",
    "-D", "non_ascii_idents",
    "-D", "private_doc_tests",
    "-D", "rust_2018_idioms",
    "-D", "single_use_lifetimes",
    "-D", "trivial_casts",
    "-D", "trivial_numeric_casts",
    "-D", "unreachable_pub",
    "-D", "unsafe_op_in_unsafe_fn",
    "-D", "unused_extern_crates",
    "-D", "unused_lifetimes",
    "-D", "unused_results",
    "-D", "variant_size_differences"
]

[build]
rustflags = ["-D", "warnings"]

[env]
RUSTFLAGS = "-D warnings" 