[package]
name = "squirrel-web"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Web interface for the Squirrel system"

[[bin]]
name = "web_server"
path = "src/bin/web_server.rs"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sqlx = { version = "0.7", features = ["runtime-tokio", "sqlite"] }

# Squirrel dependencies
squirrel-core = { path = "../core" }
squirrel-mcp = { path = "../mcp" }

[dev-dependencies]
tokio-test = { workspace = true } 