[package]
name = "squirrel-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
# Core dependencies
tokio = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
async-trait = { workspace = true, optional = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
sled = { workspace = true }

# Monitoring and logging
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true }

# MCP dependencies
bytes = { workspace = true, optional = true }
futures-util = { workspace = true, optional = true }
tokio-util = { workspace = true, optional = true }

[dev-dependencies]
tokio-test = { workspace = true }
mockall = { workspace = true }
criterion = { workspace = true }
insta = { workspace = true }
snapbox = { workspace = true }

[features]
default = ["async"]
async = ["tokio"]

[[bin]]
name = "squirrel"
path = "src/bin/main.rs"

[lib]
name = "squirrel"
path = "src/lib.rs" 